name: Post-processing


# direct push to repo is not allowed, so just listen the push event
on:
  push:
    branches:
      - main

jobs:
  post-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Skip Cache Parser Tool
        run: |
          go env -w GOPRIVATE=github.com/MeteorsLiu/llpkgstore
      - name: Set up Parser Tool
        run: |
          go install -v github.com/MeteorsLiu/llpkgstore/cmd/llpkgstore@gha-test
      - name: Run post-processing process
        run: |
          llpkgstore post-processing